/// gamescene.h
/// This file represents a QGraphicsView that updates physics in the
/// gameworld and draws them
///
/// Author: Auto Generated by QT Creator
/// Date: April 11, 2023

#ifndef GAMESCENE_H
#define GAMESCENE_H

#include <QWidget>

class gamescene : public QWidget
{

    Q_OBJECT

public:
    explicit gamescene(QWidget *parent = nullptr);

signals:

};

#endif // GAMESCENE_H
