/// main.cpp
/// This file contains the main entry point for the ProgrammingGame project
///
/// Author: Auto Generated by QT Creator
/// Date: April 11, 2023

#include "gamewindow.h"
#include "gamemodel.h"

#include <QApplication>
#include <QFontDatabase>

int main(int argc, char *argv[])
{

    QApplication a(argc, argv);

    // Load custom fonts
    QFontDatabase::addApplicationFont(":res/fonts/SourceCodePro-Regular.ttf");

    // Create model and window
    GameModel m;
    GameWindow w(m);

    w.show();
    return a.exec();

}
